[App.Jobs.Sub]
AddressToListen = "0x18Df82C7E422A42D47345Ed86B0E935E9718eBda"
EventName = "NumberChanged(uint256)"

[App.Jobs.Poller]
Interval = "1s"

[App.Metrics]
HealthReportInterval = "5s"

# NOTE: if not enabling Datadog, can omit this section.
[App.Telemetry.Datadog]
Enabled = false
StatsdAddr = ""
Namespace = ""

[App.Metrics.Prometheus]
Enabled = true
Namespace = "example"
Subsystem = "listener_app"

[ConnectionPool]
EthHTTPURLs = ["http://localhost:10545"]
EthWSURLs = ["ws://localhost:10546"]
DefaultTimeout = "5s"
HealthCheckInterval = "5s"

[App.RateLimit]
Enabled=true
Period="1m"
Rate=10
RedisAddr=""
RedisClusterMode=false
ProxyCount=1

# For Prometheus to run, must also expose the HTTP server endpoint.
[Server.HTTP]
Port = 8080
